INSERT INTO TASK_GROUP(ID, NAME) VALUES (1, 'Promocja Santander DB');
INSERT INTO TASK_GROUP(ID, NAME) VALUES (2, 'Promocja Getin DB');
INSERT INTO TASK_GROUP(ID, NAME) VALUES (3, 'Promocja Millenium DB');